language: java
sudo: false
jdk:
  - oraclejdk8
script:
  - mvn -B clean verify -Pes-1x
  - mvn -B clean verify -Pes-2x
  - mvn -B clean verify
after_success:
  - "[[ ${TRAVIS_PULL_REQUEST} == 'false' ]] && [[ ${TRAVIS_TAG} == '' ]] && mvn deploy -DskipTests --settings deploy-settings.xml"
