language: java
sudo: false
jdk:
  - oraclejdk8
before_script:
  - echo "MAVEN_OPTS=-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn" > ~/.mavenrc
install: true
script:
#  - mvn -B clean verify -Pes-1x
#  - mvn -B clean verify -Pes-2x
  - mvn -B clean verify
after_success:
  - "[[ ${TRAVIS_PULL_REQUEST} == 'false' ]] && [[ ${TRAVIS_TAG} == '' ]] && mvn deploy -DskipTests --settings deploy-settings.xml"
